name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    {}

jobs:
  build:
    name: scala-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - name: setup-java
        uses: actions/setup-java@v5
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: sbt-test
        shell: bash
        run: sbt -v +test
